; Script generated by the Inno Setup Script Wizard.
; DIOPTIMASI UNTUK PORTABLE WEB APP BUKU INDUK

#define MyAppName "Buku Induk App"
#define MyAppVersion "1.0 Alpha Version"
#define MyAppPublisher "Plex Edu Ecosystem"
#define MyAppURL "https://wahyurahmat.id/"
#define MyAppExeName "jalankan.bat"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
AppId={{6BE73787-021A-4A6C-893C-90B5979DE681}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\Buku-Induk-App
DisableProgramGroupPage=yes
LicenseFile=C:\Users\SMK Telkom Lampung\Downloads\license.txt
InfoBeforeFile=C:\Users\SMK Telkom Lampung\Downloads\info_before.txt
InfoAfterFile=C:\Users\SMK Telkom Lampung\Downloads\info_after.txt
OutputDir=C:\Project Setup
OutputBaseFilename=mysetup
SetupIconFile=C:\ProjectInstaller\logo-app.ico
SolidCompression=yes
; Refresh cache Windows agar icon baru langsung muncul
ChangesEnvironment=yes 

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Memastikan file icon dan semua file project tercopy dengan benar
Source: "C:\ProjectInstaller\logo-app.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\ProjectInstaller\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\ProjectInstaller\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; Menambahkan parameter IconFilename agar shortcut menggunakan logo aplikasi
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\logo-app.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\logo-app.ico"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec postinstall skipifsilent